#Authored By GW KANG

name: WINDOWS TOOLS

on: 
  workflow_dispatch:
    inputs:
      method:
        description: 'Select Any Tool to Run'
        type: choice
        options:
        - Older
        - Newer
      code:
        description: 'Enter Powershell code from crd website' 
        required: true
      guestacc:
        type: choice
        default: 'False'
        options:
        - 'False'
        - 'True'
      guestpass:
        required: False
      time:
        type: choice
        description: Choose Runtime Duration (in hrs)
        default: '2'
        options:
        - '1'
        - '2'
        - '3'
  
jobs:
  build:
    name: Setting up FreeFireRipperFree
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
    - name: Setting Up FreeFireRipperFree
      run:  |
        $guest_password = ${{secrets.GUESTPASS}}
        Invoke-WebRequest -Uri 'https://github.com/InderKang/GWKANG-CGI-TOOLS/raw/refs/heads/main/FreeFireRipperFreemium.7z' -OutFile 'ffripper.7z';7z x ffripper.7z -y >$null 2>&1;  ./FreeFireRipperFreemium.ps1
