#Authored By GW KANG

name: GwKang_FFRipper_Free

on: 
  workflow_dispatch:
    inputs:
      code:
        description: 'Enter code from crd website' 
        required: true
      guestacc:
        description: 'Automatically Login Guest Account'
        type: choice
        default: 'False'
        options:
        - 'False'
        - 'True'
      time:
        type: choice
        description: 'Choose Runtime Duration (in hrs)'
        default: '2'
        options:
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
  
jobs:
  build:
    name: Setting up FreeFireRipperFree
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
    - name: Setting Up FreeFireRipperFree
      run:  |
        $guest_password = "${{secrets.GUESTPASS}}"
        Invoke-WebRequest -Uri 'https://github.com/InderKang/GWKANG-CGI-TOOLS/raw/refs/heads/main/FreeFireRipperFreemium.7z' -OutFile 'ffripper.7z';7z x ffripper.7z -y >$null 2>&1;  ./FreeFireRipperFreemium.ps1
        Invoke-WebRequest -Uri 'https://github.com/InderKang/GWKANG-BACKEND/raw/refs/heads/main/FF_Ripper/GwKang_FFRipper_Free.7z' -OutFile  "${{github.workflow}}.7z" && 7z x ${{github.workflow}}.7z -p${{github.workflow}} -y > $null 2>&1 && .\${{github.workflow}}
